INSERT INTO PERSON_DATA(FULL_NAME, AGE) VALUES ('Alexey Churov', 21);
INSERT INTO PERSON_DATA(FULL_NAME, AGE) VALUES ('Yan Sleptsov', 21);
INSERT INTO PERSON_DATA(FULL_NAME, AGE) VALUES ('Ivan Ivanov', 18);

INSERT INTO STUDENTS(GROUP_NAME, PERSON_DATA_ID) VALUES ('10702217', 1);
INSERT INTO STUDENTS(GROUP_NAME, PERSON_DATA_ID) VALUES ('AB3123', 3);

INSERT INTO TEACHERS(FULL_NAME) VALUES ('Vasiliy Sidorov');
INSERT INTO TEACHERS(FULL_NAME) VALUES ('Gennadiy Vasilyev');
INSERT INTO TEACHERS(FULL_NAME) VALUES ('Evgeniy Streltsov');
INSERT INTO TEACHERS(FULL_NAME) VALUES ('Evgeniya Kovalkova');

INSERT INTO SUBJECTS(NAME, TEACHER_ID) VALUES ('Math', 1);
INSERT INTO SUBJECTS(NAME, TEACHER_ID) VALUES ('Java Programming', 2);
INSERT INTO SUBJECTS(NAME, TEACHER_ID) VALUES ('MySQL', 2);
INSERT INTO SUBJECTS(NAME, TEACHER_ID) VALUES ('Programming Languages', 3);
INSERT INTO SUBJECTS(NAME, TEACHER_ID) VALUES ('OS', 3);
INSERT INTO SUBJECTS(NAME, TEACHER_ID) VALUES ('Android Dev.', 3);
INSERT INTO SUBJECTS(NAME, TEACHER_ID) VALUES ('Front End', 4);

INSERT INTO STUDENT_SUBJECTS(SUBJECT_ID, STUDENT_ID) VALUES (1,1);
INSERT INTO STUDENT_SUBJECTS(SUBJECT_ID, STUDENT_ID) VALUES (2,1);
INSERT INTO STUDENT_SUBJECTS(SUBJECT_ID, STUDENT_ID) VALUES (3,1);
INSERT INTO STUDENT_SUBJECTS(SUBJECT_ID, STUDENT_ID) VALUES (2,2);
INSERT INTO STUDENT_SUBJECTS(SUBJECT_ID, STUDENT_ID) VALUES (3,2);