create table person_data (person_data_id bigint generated by default as identity, age integer, full_name varchar(255), primary key (person_data_id));
create table student_subjects (subject_id bigint not null, student_id bigint not null);
create table students (student_id bigint generated by default as identity, group_name varchar(255), person_data_id bigint not null, primary key (student_id));
create table subjects (subject_id bigint generated by default as identity, name varchar(255), teacher_id bigint, primary key (subject_id));
create table teachers (teacher_id bigint generated by default as identity, full_name varchar(64), primary key (teacher_id));
alter table student_subjects add constraint FKjb6x19uwrg0tewtrgv2o7ec2r foreign key (student_id) references students;
alter table student_subjects add constraint FKjuhviveo4kyikubl3suxro325 foreign key (subject_id) references subjects;
alter table students add constraint FKl3gwgs5c642kxrthdkn918atg foreign key (person_data_id) references person_data;
alter table subjects add constraint FKsjy6ghvvelraa2w9mhv3bbnys foreign key (teacher_id) references teachers;